### PR TITLE
Add a basic GitHub Actions CI script

### PR DESCRIPTION
**Pull request by arichardson**
Using https://github.com/freckle/stack-action

### CODE REVIEW

**Comment by arichardson** [comment]
Sounds like the compiler in this job is more strict. @PeterRugg @gameboo are those warnings worth fixing?

**Comment by PeterRugg** [comment]
Hmm, unless we can configure the compiler we normally use to throw the same errors, this would just be frustrating. That said, it might be worth fixing them. I don't know if we're actually confusing variables anywhere.

**Comment by arichardson** [comment]
> Hmm, unless we can configure the compiler we normally use to throw the same errors, this would just be frustrating. That said, it might be worth fixing them. I don't know if we're actually confusing variables anywhere.

I think you tell it to use a given version. Alternatively there also seems to be https://github.com/haskell/actions/tree/main/setup which allows more configuration but requires adding manual build steps instead of just relying on `stack`.

**Comment by gameboo** [comment]
I've only used github actions doing cabalisms and ghcisms before, but there may be useful things to fix here anyways. I'll see if I can reproduce locally.

**Comment by arichardson** [comment]
> I've only used github actions doing cabalisms and ghcisms before, but there may be useful things to fix here anyways. I'll see if I can reproduce locally.

The following works for me `stack clean && stack build --pedantic --ghc-options -fno-warn-unused-matches --ghc-options -fno-warn-name-shadowing`
I guess there is a similar flag to --pedantic for cabal.

**Comment by gameboo** [comment]
so looking at some of the anotations:

> XXX is not used by any defined root

sure, but, I mean... So what? I am still exporting this out of my library module... Not sure why this gives a red cross there...

**Comment by arichardson** [comment]
> so looking at some of the annotations:
> 
> > XXX is not used by any defined root
> 
> sure, but, I mean... So what? I am still exporting this out of my library module... Not sure why this gives a red cross there...
> 
> EDIT: is there a way to tell stack that I want this?

We can drop the weeder bits from this CI run, I just thought it might be helpful to find unused functions. I think we can also add additional roots to tell it that those functions should be ignored.

**Comment by gameboo** [comment]
oo fancy.

Let's drop this for now but I am having a pass fixing a bunch of warnings and I'll push on the branch if that's ok?

**Comment by gameboo** [comment]
> I think we can also add additional roots to tell it that those functions should be ignored.
It'd be nice to do this at some point

**Comment by arichardson** [comment]
> oo fancy.
> 
> Let's drop this for now but I am having a pass fixing a bunch of warnings and I'll push on the branch if that's ok?

That sounds good! I can drop the "weeder" part of this PR?

**Comment by gameboo** [comment]
yeah let's drop it for now
I just finished building with full pedantic except for the orphan class thing but there is no real story to tackle that one in general... We had discussion already on where this code ought to live but from what I remember we don't think it should go near the type. so, -fno-warn

**Comment by gameboo** [comment]
@arichardson I reverted my commits which seemed to merge in a recent master and update the ci script to remove the weeder, and add a build step as well. I will merge this PR and we can add a weeder at some point if we want.

I'll probably also have a pass at re implementing these commits I reverted at some point...

**Review by marnovandermaas — COMMENTED** [review]
Do you mind removing the commits from the PR instead of reverting them? This keeps the history of the main branch cleaner.

You can do this with the command:
`git rebase -i HEAD~12`

Then dropping the commits and the reversion as needed.

**Comment by gameboo** [comment]
Sure thing. I'll create a branch somewhere though, because I am keen to hold on to the changesets somewhere (I'll eventually want to implement these).

**Comment by gameboo** [comment]
@marnovandermaas done!

**Review by PeterRugg — APPROVED** [review]

**Pull request merged**
